# Laad standaard set van integraties. Niet verwijderen.
default_config:

# Laad frontend thema's uit de themes-map
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_select:
  zendure_2400_ac_modus_selecteren:
    name: Zendure 2400 AC Modus Selecteren
    icon: mdi:battery-charging-wireless
    options:
      - Standby
      - Handmatig
      - Nul op de meter
      - Alleen slim ontladen
      - Alleen slim opladen
      - Opladen met 2400 watt
      - Ontladen met 2400 watt

input_number:
  zendure_2400_ac_handmatig_vermogen:
    name: Zendure 2400 AC Handmatig Vermogen
    min: -2400
    max: 2400
    step: 1
    mode: box
    unit_of_measurement: "W"

sensor:
  - platform: integration
    name: "Zendure 2400 AC Energie Import"
    unique_id: zendure_2400_ac_energie_import
    source: sensor.zendure_2400_ac_vermogen_import
    unit_prefix: k
    round: 2
    method: trapezoidal

  - platform: integration
    name: "Zendure 2400 AC Energie Export"
    unique_id: zendure_2400_ac_energie_export
    source: sensor.zendure_2400_ac_vermogen_export
    unit_prefix: k
    round: 2
    method: trapezoidal

template:
  - sensor:
      - name: "Zendure 2400 AC Indicatie Beschikbare Energie"
        unit_of_measurement: "kWh"
        state_class: measurement
        device_class: energy
        state: >
          {% set laad = states('sensor.zendure_2400_ac_laadpercentage') | float(0) %}
          {% set min_laad = states('sensor.zendure_2400_ac_minimale_laadpercentage') | float(0) %}
          {% set aantal_batterijen = states('sensor.zendure_2400_ac_aantal_batterijen') | float(1) %}
          {% set capaciteit_per_batterij = 2.88 %}
          {% set totale_capaciteit = aantal_batterijen * capaciteit_per_batterij %}
          {% set bruikbaar_percentage = laad - min_laad %}

          {% if bruikbaar_percentage < 0 %}
            0
          {% else %}
            {{ (bruikbaar_percentage / 100 * totale_capaciteit) | round(2) }}
          {% endif %}
        unique_id: Zendure_2400_AC_Indicatie_Beschikbare_Energie
        icon: mdi:lightning-bolt-circle

      - name: "Zendure 2400 AC RTE Totaal"
        unit_of_measurement: "%"
        state_class: measurement
        icon: mdi:percent-box
        state: >
          {% set energy_import = states('sensor.zendure_2400_ac_energie_import') | float(0) %}
          {% set energy_export = states('sensor.zendure_2400_ac_energie_export') | float(0) %}
          {% if energy_import > 0 %}
            {% set percentage = ((energy_export / energy_import) * 100) | round(2) %}
            {% if 0 <= percentage <= 100 %}
              {{ percentage }}
            {% else %}
              0
            {% endif %}
          {% else %}
            0
          {% endif %}
        unique_id: Zendure_2400_AC_RTE_Totaal

rest:
  - resource: http://<IP-BATTERIJ>/properties/report
    scan_interval: 1
    sensor:
      - name: "Zendure 2400 AC Vermogen Export"
        value_template: "{{ value_json['properties']['packInputPower'] | int }}"
        unique_id: Zendure_2400_AC_Vermogen_Export
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power

      - name: "Zendure 2400 AC Vermogen Import"
        value_template: "{{ (value_json['properties']['outputPackPower'] | int) }}"
        unique_id: Zendure_2400_AC_Vermogen_Import
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power

      - name: "Zendure 2400 AC Signaalsterkte"
        value_template: >
          {% set rssi = value_json['properties']['rssi'] | int(-100) %}
          {% if rssi >= -60 %}
            Uitstekend
          {% elif rssi >= -70 %}
            Goed
          {% elif rssi >= -80 %}
            Zwak
          {% else %}
            Slecht
          {% endif %}
        unique_id: Zendure_2400_AC_Signaalsterkte
        icon: mdi:wifi

      - name: "Zendure 2400 AC Batterij 1 Temperatuur"
        value_template: >
          {% set maxTemp = value_json['packData'][0]['maxTemp'] | int %}
          {{ (maxTemp - 2731) / 10.0 }}
        unique_id: Zendure_2400_AC_Batterij_1_Temperatuur
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        icon: mdi:thermometer

      - name: "Zendure 2400 AC Batterij 2 Temperatuur"
        value_template: >
          {% set maxTemp = value_json['packData'][1]['maxTemp'] | int %}
          {{ (maxTemp - 2731) / 10.0 }}
        unique_id: Zendure_2400_AC_Batterij_2_Temperatuur
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        icon: mdi:thermometer

      - name: "Zendure 2400 AC Batterij 3 Temperatuur"
        value_template: >
          {% set maxTemp = value_json['packData'][2]['maxTemp'] | int %}
          {{ (maxTemp - 2731) / 10.0 }}
        unique_id: Zendure_2400_AC_Batterij_3_Temperatuur
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        icon: mdi:thermometer

      - name: "Zendure 2400 AC Batterij 4 Temperatuur"
        value_template: >
          {% set maxTemp = value_json['packData'][3]['maxTemp'] | int %}
          {{ (maxTemp - 2731) / 10.0 }}
        unique_id: Zendure_2400_AC_Batterij_4_Temperatuur
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        icon: mdi:thermometer

      - name: "Zendure 2400 AC Batterij 5 Temperatuur"
        value_template: >
          {% set maxTemp = value_json['packData'][4]['maxTemp'] | int %}
          {{ (maxTemp - 2731) / 10.0 }}
        unique_id: Zendure_2400_AC_Batterij_5_Temperatuur
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        icon: mdi:thermometer

      - name: "Zendure 2400 AC Batterij 6 Temperatuur"
        value_template: >
          {% set maxTemp = value_json['packData'][5]['maxTemp'] | int %}
          {{ (maxTemp - 2731) / 10.0 }}
        unique_id: Zendure_2400_AC_Batterij_6_Temperatuur
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        icon: mdi:thermometer

      - name: "Zendure 2400 AC Vermogen Aansturing"
        value_template: >
          {% set opladen = value_json['properties']['outputPackPower'] | int %}
          {% set ontladen = - (value_json['properties']['packInputPower'] | int) %}
          {% if opladen != 0 %}
            {{ opladen }}
          {% else %}
            {{ ontladen }}
          {% endif %}
        unique_id: Zendure_2400_AC_Vermogen_Aansturing
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power

      - name: "Zendure 2400 AC Aantal Batterijen"
        value_template: "{{ value_json['properties']['packNum'] }}"
        unique_id: Zendure_2400_AC_Aantal_Batterijen
        icon: mdi:battery

      - name: "Zendure 2400 AC Opslagmodus"
        value_template: >
          {% set states = {1: "Opslaan in RAM", 0: "Opslaan in Flash"} %}
          {% set packState = value_json['properties']['smartMode'] | int %}
          {{ states.get(packState, "Onbekend") }}
        unique_id: Zendure_2400_AC_Opslagmodus
        icon: mdi:floppy

      - name: "Zendure 2400 AC Batterijspanning"
        value_template: "{{ (value_json['properties']['BatVolt'] | float / 100) | round(2) }}"
        unique_id: Zendure_2400_AC_Batterijspanning
        unit_of_measurement: "V"
        state_class: measurement
        device_class: voltage
        icon: mdi:sine-wave

      - name: "Zendure 2400 AC Resterende Ontlaad Tijd"
        value_template: >
         {% set vermogen_aansturing = states('sensor.zendure_2400_ac_vermogen_aansturing') | float(0) %}
         {% if vermogen_aansturing < 0 %}
         {% set total_minutes = value_json['properties']['remainOutTime'] | float(0) %}
         {% set hours = (total_minutes // 60) | int %}
         {% set minutes = (total_minutes % 60) | int %}
          {{ hours }}u {{ minutes }}m
         {% else %}
          Niet aan het ontladen
         {% endif %}
        icon: mdi:clock-time-eight-outline
        unique_id: zendure_2400_ac_resterende_ontlaad_tijd

      - name: "Zendure 2400 AC Omvormer Temperatuur"
        value_template: >
          {% set maxTemp = value_json['properties']['hyperTmp'] | int %}
          {{ (maxTemp - 2731) / 10.0 }}
        unique_id: Zendure_2400_AC_Omvormer_Temperatuur
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        icon: mdi:thermometer

      - name: "Zendure 2400 AC Laadpercentage"
        value_template: "{{ value_json['properties']['electricLevel'] }}"
        device_class: battery
        unit_of_measurement: "%"
        state_class: measurement
        unique_id: Zendure_2400_AC_Laadpercentage

      - name: "Zendure 2400 AC Minimale Laadpercentage"
        value_template: "{{ (value_json['properties']['minSoc'] | int / 10) | int }}"
        device_class: battery
        unit_of_measurement: "%"
        state_class: measurement
        unique_id: Zendure_2400_AC_Minimale_Laadpercentage
        icon: mdi:battery-high

      - name: "Zendure 2400 AC Maximale Laadpercentage"
        value_template: "{{ (value_json['properties']['socSet'] | int / 10) | int }}"
        device_class: battery
        unit_of_measurement: "%"
        state_class: measurement
        unique_id: Zendure_2400_AC_Maximale_Laadpercentage
        icon: mdi:battery-high

      - name: "Zendure 2400 AC Modus"
        value_template: >
          {% set states = {1: "Opladen", 2: "Ontladen"} %}
          {% set packState = value_json['properties']['acMode'] | int %}
          {{ states.get(packState, "Onbekend") }}
        unique_id: Zendure_2400_AC_Modus
        icon: mdi:battery-charging-wireless

      - name: "Zendure 2400 AC Error"
        value_template: >
          {% set states = {0: "Geen meldingen", 1: "Zie Zendure APP"} %}
          {% set packState = value_json['properties']['is_error'] | int %}
          {{ states.get(packState, "Onbekend") }}
        unique_id: Zendure_2400_AC_Error
        icon: mdi:battery-alert

      - name: "Zendure 2400 AC SOC Status"
        value_template: >
          {% set states = {0: "Goed", 1: "Kalibreren"} %}
          {% set packState = value_json['properties']['socStatus'] | int %}
          {{ states.get(packState, "Onbekend") }}
        unique_id: Zendure_2400_AC_SOC_Status
        icon: mdi:battery-heart-variant

      - name: "Zendure 2400 AC Ingesteld Ontlaadvermogen"
        value_template: "{{ value_json['properties']['outputLimit'] }}"
        unique_id: Zendure_2400_AC_Ingesteld_Ontlaadvermogen
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power

      - name: "Zendure 2400 AC Ingesteld Oplaadvermogen"
        value_template: "{{ value_json['properties']['inputLimit'] }}"
        unique_id: Zendure_2400_AC_Ingesteld_Oplaadvermogen
        unit_of_measurement: "W"
        state_class: measurement
        device_class: power

  - resource: http://<IP-HOMEWIZARD-P1>/api/v1/data   # IP-adres van je Homewizard P1 voor V1 API
    scan_interval: 1
    sensor:
      - name: "P1 Aansturing API v1"
        value_template: "{{ value_json.active_power_w | float }}"
        unique_id: P1_Aansturing_API_V1
        unit_of_measurement: "W"
        device_class: power

rest_command:
  zendure_opslaan_in_ram:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"smartMode": 1 }}'

  zendure_snel_laden:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"acMode": 1, "inputLimit": 2400 }}'

  zendure_stop_met_laden:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"acMode": 1, "inputLimit": 0 }}'

  zendure_x_laden:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"acMode": 1, "inputLimit": {{inputLimit}} }}'

  zendure_x_laden_balanceren:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"inputLimit": {{inputLimit}} }}'

  zendure_x_ontladen:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"acMode": 2, "outputLimit": {{outputLimit}} }}'

  zendure_x_ontladen_balanceren:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"outputLimit": {{outputLimit}} }}'

  zendure_snel_ontladen:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"acMode": 2, "outputLimit": 2400 }}'

  zendure_stop_met_ontladen:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"acMode": 2, "outputLimit": 0 }}'

  zendure_stop_met_alles:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"outputLimit": 0, "inputLimit": 0 }}'

  zendure_standby:
    url: http://<IP-BATTERIJ>/properties/write
    method: POST
    payload: '{"sn":"<SERIAL-2400AC>","properties":{"smartMode": 0, "outputLimit": 0, "inputLimit": 0 }}'
